spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: update

front-url:
  https://checkmoi.vercel.app
