spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: profile_nickname, profile_image, account_email, birthday
            redirect-uri: ${SERVER_NAME}/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

jwt:
  issuer: checkMoi
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expire-length: 3600000
  refresh-token:
    expire-length: 7200000

cors:
  allowed:
    api: /**
    method: '*'
    origin:
      - http://localhost:3000
      - https://checkmoi.vercel.app
      - http://localhost:6006
      - https://dev.checkmoi.ga
      - https://checkmoi.ga

security:
  patterns:
    ignoring:
      ALL:
        - /static/**
        - /favicon.ico
        - /h2-console/**
      GET:
        - /
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
    permit-all:
      ALL:
        - /
        - /docs/**
      GET:
        - /api/tokens/**
        - /api/books/**
        - /api/studies/**
        - /login
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
      OPTIONS: /**
