spring:
  profiles:
    active: local
    include: |
      security,
      aws
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  task:
    scheduling:
      pool:
        size: 2
front-url:
  http://localhost:8080
