spring:
  profiles:
    active: local
    include: |
      security,
      aws
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

front-url:
  http://localhost:8080
