spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver

  jpa:
    database: H2
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: create

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: test
            client-secret: test
            scope: test
            redirect-uri: test
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization_uri: test
            token_uri: test
            user-info-uri: test
            user_name_attribute: test

jwt:
  issuer: test
  secret-key: XtvCnK/4CRsblAWCjeh22VAyXGjszJLR4xVQJ8CNTVk=
  access-token:
    expire-length: 60_000
  refresh-token:
    expire-length: 3_600_000
cloud:
  aws:
    s3:
      region: ap-northeast-2
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
      url: ${S3_URL}
      bucketName: ${S3_INTEGRATED_BUCKET_NAME}

cors:
  allowed:
    api: /**
    method: '*'
    origin:
      - http://localhost:8080

security:
  patterns:
    ignoring:
      ALL:
        - /static/**
        - /favicon.ico
      GET:
        - /api/tokens/**
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
    permit-all:
      ALL: [ ]
      GET:
        - /api/tokens/**
        - /api/**/books/**
        - /api/**/studies/**
        - /login
      POST: [ ]
      PATCH: [ ]
      PUT: [ ]
      DELETE: [ ]
      OPTIONS: /**

front-url:
  http://localhost:8080
