spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: profile_nickname, profile_image, account_email, birthday
            redirect-uri: ${SERVER_NAME}/login/oauth2/code/{registrationId}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

jwt:
  issuer: checkMoi
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expire-length: 3600000
  refresh-token:
    expire-length: 7200000

front-url:
  http://localhost:3000
